### 1) Import the numpy package under the name np

In [ ]:
import numpy as np

#### 2) Print the numpy version and the configuration

In [ ]:
print(np.__version__)

2.0.2


#### 3) Create a null vector of size 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4) How to find the memory size of any array

In [ ]:
x = np.array([1,2,3,4])


print(f"{x.itemsize * x.size} Bytes" )



32 Bytes


#### 5) How to get the documentation of the numpy add function from the command line?

In [ ]:
print(help(np.add))

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6) Create a null vector of size 10 but the fifth value which is 1

In [ ]:
x = np.zeros(10)

x[4] = 1

print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7) Create a vector with values ranging from 10 to 49

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8) Reverse a vector (first element becomes last)

In [ ]:
np.arange(1,10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

#### 9) Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10) Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11) Create a 3x3 identity matrix

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12) Create a 3x3x3 array with random values

In [ ]:
np.random.randint(0,9,size=27).reshape((3,3,3))

array([[[0, 4, 4],
        [2, 6, 7],
        [5, 8, 0]],

       [[8, 4, 7],
        [1, 3, 0],
        [0, 3, 0]],

       [[6, 2, 0],
        [1, 6, 4],
        [4, 2, 6]]])

#### 13) Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
x = np.random.randint(0,100,size=100).reshape(10,10)

print(x)

print("min Value:",x.min())
print("max Value:",x.max())

[[61 63 57 15 77 93 89 48 20 39]
 [16 49  6 96 61 13 52 85 60 61]
 [ 2 87 97 84 12 67 11 21 86 42]
 [29 57 44 20 62 64 86 70 13 61]
 [69 51 62 14 41  3 83 67  8 34]
 [90 55 52 72 46 43 98 45 42 27]
 [65 61 73  7 78 99  2  6 30 28]
 [70 28 94 84 11  4 17 54 99 83]
 [74 21  3 92 69 75 34  0 16 70]
 [83 44 59 76 14 83 52 69 68 85]]
min Value: 0
max Value: 99


#### 14) Create a random vector of size 30 and find the mean value

In [ ]:
x = np.random.random(size=30)

print(x)
print("Mean", x.mean())

[0.31113759 0.93607563 0.35819082 0.28463614 0.73232906 0.86699263
 0.27683528 0.30963066 0.18623323 0.32540202 0.1272591  0.82922654
 0.77517557 0.5393155  0.57296417 0.86586078 0.69526283 0.25307022
 0.36626939 0.88190215 0.57341111 0.68615976 0.59568954 0.42321115
 0.49814284 0.20571108 0.63712623 0.73128308 0.85519532 0.01272088]
Mean 0.523747343844704


#### 15) Create a 2d array with 1 on the border and 0 inside

In [ ]:
a = np.ones((10,10))

a[1:-1,1:-1] = 0

print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16} How to add a border (filled with 0's) around an existing array?

In [ ]:
np.random.seed(1)
x = np.random.randint(1,100,size=100).reshape((10,10))

x[0] = 0

x[-1] = 0

x[:,0] = 0
x[:,-1] = 0
print(x)


[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0 72  7 26 51 21 19 85 12  0]
 [ 0 15 51 69 88 88 95 97 87  0]
 [ 0  8 64 62 23 58  2  1 61  0]
 [ 0 89 14 48 73 31 72  4 71  0]
 [ 0 58  4 69 25 44 77 27 53  0]
 [ 0 83 16 65 69 26 99 88  8  0]
 [ 0 23 10 68 24 28 38 58 84  0]
 [ 0 33 35 11 24 16 88 26 72  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


#### 17) What is the result of the following expression?

```
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print("0 * np.nan ==> {}".format(0*np.nan))
print("np.nan == np.nan ==> {} ".format(np.nan == np.nan))
print("np.inf > np.nan ==> {} ".format(np.inf > np.nan))
print("np.nan - np.nan ==> {} ".format(np.nan - np.nan))
print("np.nan in set([np.nan]) ==> {}".format(np.nan in set([np.nan])))
print("0.3 == 3 * 0.1 ==> {} ".format(0.3 == 3 * 0.1))

0 * np.nan ==> nan
np.nan == np.nan ==> False 
np.inf > np.nan ==> False 
np.nan - np.nan ==> nan 
np.nan in set([np.nan]) ==> True
0.3 == 3 * 0.1 ==> False 


#### 18) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19) Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
x = np.zeros((8,8))

x[::2,::2] = 1

x[1::2,1::2] = 1

x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20) Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21) Create a checkerboard 8x8 matrix using the tile function

In [ ]:
np.tile([[1,0],[0,1]],(8,8))

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

#### 22) Normalize a 5x5 random matrix (Using Z-score Normalization)

In [ ]:
np.random.seed(1)
x = np.random.random(25).reshape(5,5)
print("X Values\n",x)

x_normaized = (x - np.mean(x)) / np.std(x)
print("\nX_Normalized Values\n\n",x_normaized)

X Values
 [[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01]
 [9.23385948e-02 1.86260211e-01 3.45560727e-01 3.96767474e-01
  5.38816734e-01]
 [4.19194514e-01 6.85219500e-01 2.04452250e-01 8.78117436e-01
  2.73875932e-02]
 [6.70467510e-01 4.17304802e-01 5.58689828e-01 1.40386939e-01
  1.98101489e-01]
 [8.00744569e-01 9.68261576e-01 3.13424178e-01 6.92322616e-01
  8.76389152e-01]]

X_Normalized Values

 [[-0.08166511  1.00240927 -1.57179097 -0.4915921  -1.04765972]
 [-1.24215993 -0.906462   -0.33708451 -0.15405956  0.35365788]
 [-0.07390005  0.87693577 -0.84143938  1.56639833 -1.47431007]
 [ 0.82420869 -0.08065433  0.42468899 -1.07042386 -0.86413849]
 [ 1.28984952  1.88859468 -0.45194809  0.90232398  1.56022104]]


#### 23) Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [ ]:
data_type = np.dtype([
    ('r',np.ubyte),
    ('g',np.ubyte),
    ('b',np.ubyte),
    ('a',np.ubyte)
])

data_type

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24) Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)



In [ ]:
np.matmul(np.random.randint(1,10,size=15).reshape(5,3),(np.random.randint(1,10,size=6).reshape(3,2)))

array([[74, 44],
       [71, 49],
       [55, 41],
       [39, 27],
       [40, 53]])

#### 25) Given a 1D array, negate all elements which are between 3 and 8, in place.

In [ ]:
x = np.arange(1,10)

x[(x > 3) & (x < 8)] *= -1

x

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26)  What is the output of the following script?


```print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))



9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```


In [ ]:
x = np.arange(1,10)

try:
    print("X ** X ==> {}".format(x**x))
    print("2 << X >> 2 ==> {}".format(2<<x>>2))
    print("X < -X ==> {}".format(x<-x))
    print("1j * X ==> {}".format(1j*x))
    print("X/1/1 ==> {}".format(x/1/1))
    print("X < X > X  ==> {}".format(x<x>x))

except:
    print("Not Legal")

X ** X ==> [        1         4        27       256      3125     46656    823543
  16777216 387420489]
2 << X >> 2 ==> [  1   2   4   8  16  32  64 128 256]
X < -X ==> [False False False False False False False False False]
1j * X ==> [0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
X/1/1 ==> [1. 2. 3. 4. 5. 6. 7. 8. 9.]
Not Legal


28. What are the result of the following expressions? (★☆☆)

```
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


/tmp/ipython-input-1422587819.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-1422587819.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-1422587819.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29) How to round away from zero a float array ?

In [ ]:
np.random.seed(1)
x = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(x)), x))



[ -2.   5. -10.  -4.  -8.  -9.  -7.  -4.  -3.   1.]


#### 30) How to find common values between two arrays?

In [ ]:
x = np.random.randint(0,10,20)
y = np.random.randint(0,10,10)

np.intersect1d(x,y)

array([1, 5, 6, 7, 9])

#### 31) How to ignore all numpy warnings (not recommended)?

In [ ]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)

1) Is the following expressions true?
```
np.sqrt(-1) == np.emath.sqrt(-1)
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))


False
False


/tmp/ipython-input-768763011.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))
/tmp/ipython-input-768763011.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33) How to get the dates of yesterday, today and tomorrow?

In [ ]:
print("Today's date ==> {}".format(np.datetime64('Today')))
print("Yesterday's date ==> {}".format(np.datetime64('Today') - np.timedelta64(1)))
print("Tomorrows's date ==> {}".format(np.datetime64('Today') + np.timedelta64(1)))

Today's date ==> 2025-09-14
Yesterday's date ==> 2025-09-13
Tomorrows's date ==> 2025-09-15
